name: Terraform-workflow-WE

on: 
  workflow_dispatch:
  # push:
    # branches: [ main ]
    # paths:
    #   - '**.tf'
    
env:
  TF_IN_AUTOMATION: true
  TF_INPUT: false
  
permissions:
  id-token: write
  contents: read

jobs:
  plan:
    runs-on: self-hosted
    
    steps:
      - name: Checkout foundation-azure-infra-app-we Repository
        uses: actions/checkout@v4
        with:
          path: main-repo
          
      
      - name: Checkout 002-ccoe-infra-modules
        uses: actions/checkout@v4
        with:
          repository: bkainth1/terraform-repo
          ref: main
          path: 002-ccoe-infra-modules
          #token: ${{ secrets.TERRAFORM_REPO }}
      - name: Install Azure cli
        run: |
          sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
          curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
          AZ_REPO=$(lsb_release -cs)
          echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
          sudo apt-get update
          sudo apt-get install azure-cli
          
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        
      - name: Terraform init
        working-directory: main-repo
        run: |
            terraform init
            

      - name: Terraform Validate
        working-directory: main-repo
        run: |
            terraform validate

      - name: Terraform Plan
        working-directory: main-repo
        run: |
            terraform plan -out=tfplan
            

      - name: Save Plan
        uses: actions/upload-artifact@v4
        with:
          name: tf-plan-${{ github.run_number }}
          path: |
            main-repo/tfplan
            main-repo/paln.txt

      - name: Terraform Apply
        working-directory: main-repo
        run: |
            terraform apply --auto-approve
