name: Terraform-workflow-WE

on: 
  workflow_dispatch:
  # push:
    # branches: [ main ]
    # paths:
    #   - '**.tf'
    
env:
  TF_IN_AUTOMATION: true
  TF_INPUT: false

jobs:
  plan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout foundation-azure-infra-app-we Repository
        uses: actions/checkout@v4

      
      - name: Checkout 002-ccoe-infra-modules
        uses: actions/checkout@v4
        with:
          repository: bkainth1/terraform-repo
          token: ${{ secrets.TERRAFORM_REPO }}
          ref: main
          path: 002-ccoe-infra-modules

      - name: Check directory
        run: |
           ls -lrt
           cd 002-ccoe-infra-modules
           ls -lrt

    

       
